controller:
  admin:
    username: admin
    password: admin123

  serviceType: LoadBalancer
  servicePort: 80
  service:
    port: 80
    targetPort: 8080

  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"
    requests:
      cpu: "250m"
      memory: "512Mi"

  persistentVolume:
    enabled: true
    storageClass: "ebs-sc"
    size: 8Gi

  installPlugins:
    - kubernetes:latest
    - workflow-aggregator:latest
    - git:latest
    - configuration-as-code:latest
    - credentials-binding:latest
    - github:latest
    - docker-plugin:latest
    - docker-workflow:latest
    - job-dsl:latest

  serviceAccount:
     name: jenkins-sa
     create: false
  JCasC:
    configScripts:
      script-approval: |
        unclassified:
          scriptApproval:
            approvedSignatures:
              - "new javaposse.jobdsl.dsl.DslScriptLoader java.lang.String java.lang.ClassLoader"
              - "method org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition create org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition"