server:
  service:
    type: LoadBalancer
    port: 443

applications:
  - name: example-app
    namespace: default
    project: default
    source:
      repoURL: https://github.com/olexandrd/microservice-project.git
      path: charts/django-app
      targetRevision: cd
      helm:
        valueFiles:
          - values.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

repositories:
  - name: example-app
    url: https://github.com/olexandrd/microservice-project.git


repoConfig:
  insecure: "true"
  enableLfs: "true"
