image:
  repository: 290480495560.dkr.ecr.us-east-2.amazonaws.com/app
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  host: django.stage.fixer.tools
  path: /
  pathType: Prefix
  tls: true

config:
  POSTGRES_HOST: django-postgresql 
  POSTGRES_PORT: 5432
  POSTGRES_USER: django_user &postgres_user
  POSTGRES_NAME: django_db &postgres_name
  POSTGRES_PASSWORD: pass9764gd &postgres_password
  ALLOWED_HOSTS: django.stage.fixer.tools

postgresql:
  enabled: false
  global:
    postgresql:
      auth:
        postgresPassword: *postgres_password
        username: *postgres_user
        database: *postgres_name
        password: *postgres_password
  primary:
    persistence:
      size: 2Gi