image:
  repository: 290480495560.dkr.ecr.us-east-2.amazonaws.com/lesson-7-ecr
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  host: django.stage.fixer.tools
  path: /
  pathType: Prefix
  tls: true

config:
  POSTGRES_HOST: django-postgresql
  POSTGRES_PORT: 5432
  POSTGRES_USER: django_user
  POSTGRES_NAME: django_db
  POSTGRES_PASSWORD: pass9764gd
  ALLOWED_HOSTS: django.stage.fixer.tools

postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        postgresPassword: pass9764gd
        username: django_user
        database: django_db
        password: pass9764gd
  primary:
    persistence:
      size: 2Gi